version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      NODE_ENV: "development"
      PORT: "8080"
      HOST: "localhost"

      CORS_ORIGIN: "http://localhost:*"

      COMMON_RATE_LIMIT_WINDOW_MS: "1000"
      COMMON_RATE_LIMIT_MAX_REQUESTS: "20"
      DATABASE_URL: "postgresql://backend:backend_password@db:5432/postdonbass_db"
  db:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend_password
      POSTGRES_DB: postdonbass_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: