version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: "development"
      PORT: "8080"
      HOST: "localhost"

      CORS_ORIGIN: "http://localhost:*"

      COMMON_RATE_LIMIT_WINDOW_MS: "1000"
      COMMON_RATE_LIMIT_MAX_REQUESTS: "20"
      DATABASE_URL: "postgresql://backend:backend_password@db:5432/postdonbass_db"
    command: >
      sh -c "npx prisma db push --accept-data-loss; npx prisma db seed; npm run start"
  db:
    image: postgres:17
    container_name: database
    environment:
      POSTGRES_USER: backend
      POSTGRES_PASSWORD: backend_password
      POSTGRES_DB: postdonbass_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data: